const data = [
  {
    id: 1,
    name: "amber",
    size: "1 carat",
    price: "2200",
    image: "/Listitems/Amber.jpg",
  },
  {
    id: 2,
    name: "amethyst",
    size: "1 carat",
    price: "2500",
    image: "/Listitems/Amethyst.jpg",
  },
  {
    id: 3,
    name: "aquamarine",
    size: "1 carat",
    price: "2400",
    image: "/Listitems/Aquamarine.jpg",
  },
  {
    id: 4,
    name: "citrine",
    size: "1 carat",
    price: "1200",
    image: "/Listitems/Citrine.jpg",
  },
  {
    id: 5,
    name: "diamond",
    size: "1 carat",
    price: "1400",
    image: "/Listitems/Diamond.jpg",
  },
  {
    id: 6,
    name: "emerald",
    size: "1 carat",
    price: "3000",
    image: "/Listitems/Emerald.jpg",
  },
  {
    id: 7,
    name: "moonstone",
    size: "1 carat",
    price: "1200",
    image: "/Listitems/Moonstone.jpg",
  },
  {
    id: 8,
    name: "ruby",
    size: "1 carat",
    price: "2000",
    image: "/Listitems/Ruby.jpg",
  },
  {
    id: 9,
    name: "sapphire",
    size: "1 carat",
    price: "2200",
    image: "/Listitems/Sapphire.jpg",
  },
  {
    id: 10,
    name: "topaz",
    size: "1 carat",
    price: "2000",
    image: "/Listitems/Topaz.jpg",
  },
];
export default data;
